### ISSUE TITLE
Clarification needed: What should npm test do?

### ISSUE THREAD

**Issue by YueYan4** [comp426-2022-fall/a04#1]
#### URL of file with confusing thing
https://github.com/comp426-2022-fall/a04/

#### Line number of confusing thing
Last test; "Run a test"

#### What is confusing?
I'm confused on what I should do after I console.log the port. npm test times out.

#### What do you think the confusing thing means?
I think I need to close the port/set the timeout but I'm not sure how.

#### What did you read to try to understand better what is happening and solve the issue?
I tried looking at express' documentation and how to do server.close and timeout but neither worked.

**Comment by daqichen** [comment]
In `autograding.json`, under "Test script"
```
"timeout": 1,
```
The other tests all have that field set to 10, could this be the reason why it's timing out?

**Comment by jdmar3** [comment]
I shortened the timeout for that one so that it would kill the test once it came up, but I think I need to actually configure it with an internal timeout that kills the process so that the error doesn't happen. I'll look at it.

**Comment by YueYan4** [comment]
It works now, thank you!
