### ISSUE TITLE
Autograder: "Roll random dice" Failing, Suspecting Missing Escape Quotemarks

### ISSUE THREAD

**Issue by daqichen** [comp426-2022-fall/a04#3]
#### Which autograder check is failing?
Roll random dice

#### What is happening?
The output for test Roll random dice did not match

#### Failed workflow run URL
https://github.com/comp426-2022-fall/a04-daqichen/actions/runs/3421300556/jobs/5697256051
LINE 111
```
::error::The output for test Roll random dice did not match%0AExpected:%0A{"sides":([4-9]|1[0-9]|20),"dice":([1-4]),"rolls":([1-3]),"results":\[(([1-9]|[1-7][0-9]|80),?){0,2}(([1-9]|[1-7][0-9]|80)\])}%0AActual:%0A{ _: [], port: 19055 }%0AServer listening on port 19055%0AGot body: { sides: '${SIDES}', dice: '${DICE}', rolls: '${ROLLS}' }%0A{"sides":"${SIDES}","dice":"${DICE}","rolls":"${ROLLS}","results":[]}
```

#### What should be happening? & Why do you think the autograder is failing? 

``` bash
"PORT=\"$(shuf -i 2000-65535 -n 1)\"; SIDES=\"$(shuf -i 4-20 -n 1)\"; DICE=\"$(shuf -i 1-4 -n 1)\"; ROLLS=\"$(shuf -i 1-3 -n 1)\"; (timeout --signal=SIGINT 5 node server.js --port=$PORT; exit 0) & sleep 1s && curl -s -d 'sides=${SIDES}&dice=${DICE}&rolls=${ROLLS}' http://localhost:${PORT}/app/roll/ && sleep 5s"
```
I suspect that `'sides=${SIDES}&dice=${DICE}&rolls=${ROLLS}' ` needs to escape the Quotemarks LIKE SO:
```bash
'sides=$\{SIDES\}&dice=$\{DICE\}&rolls=$\{ROLLS\}' 
``` 
Because right now, it's taking in `${SIDES}`, `${DICE}`, and `${ROLLS}` as literal inputs instead of variables. Earlier I was logging the req body, they were showing up as those literal strings.

#### Screenshots of your local test(s)
<img width="385" alt="image" src="https://user-images.githubusercontent.com/55526292/200633901-60736a3b-b6d7-45ba-b11a-898fb32ecf72.png">

**Comment by jdmar3** [comment]
I think you're exactly right. I just updated it. Let's see if that works better.

**Comment by jdmar3** [comment]
And, if not, I'll update it again. :)

**Comment by daqichen** [comment]
It failed with the same error, we can maybe try discarding the curly braces for inside the "":
Instead of
```
'sides=\"$SIDES\"&dice=\"$DICE\"&rolls=\"$ROLLS\"'
```
Try
```
'sides=$SIDES&dice=$DICE&rolls=$ROLLS'
```
I am unable to replicate it exactly on my local, since the ${PORT} is working in grader environment but it errors out on my local machine, but using '$SIDES', etc., I can log out the values the environment variables evaluate to, instead of the literal names.

**Comment by niharcv** [comment]
@jdmar3 The reason this is failing is because in Bash you can only insert variables inside double quotes, ie " and not '.

Please update the autograder to use 

**"**sides=${SIDES}&dice=${DICE}&rolls=${ROLLS}**"** 

instead of 

'sides=${SIDES}&dice=${DICE}&rolls=${ROLLS}'

and the issue will be fixed!

**Comment by jdmar3** [comment]
Of course you are correct. I don't know what I was thinking. Thanks!
