### ISSUE TITLE
Autograder

### ISSUE THREAD

**Issue by mayather** [comp426-2022-fall/a04#5]
<img width="724" alt="Capture 5" src="https://user-images.githubusercontent.com/69762402/204156858-a09eb64f-dbb9-43f5-94bd-9d3c11636f2c.PNG">
I'm not exactly sure what these autograder errors mean. For the first error, if it's an issue with my node version, I haven't gotten their error for any of my other assignments.

**Comment by vennila-t** [comment]
Seems like you figured it out! Feel free to comment any issues you run into later.
