### ISSUE TITLE
Autograder: [DESCRIBE BUG BEHAVIOR]

### ISSUE THREAD

**Issue by chaynickUNC** [comp426-2022-fall/a04#7]
If you think the autograder has a bug, go through this checklist:

- [ ] Did you search or read through the other issues on this repo to make sure there isn't already a related issue?
- [ ] Did you run and test your code on your local machine?
- [ ] Did your code execute without errors on your local machine?
- [ ] Did your code run as expected on your local machine?

None of the above, create an issue
------------------------------------------------------------------

Make sure to add **all the information needed to understand the error** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Identify which autograder check is failing.
- [ ] Explain what is happening. 
- [ ] Provied URL to failed autograder action. (Click the Actions tab in _your_ assignment repository and get the URL next to the most recent workflow run.)
- [ ] Explain what you think should be happening.
- [ ] Provide **_screenshots_** of your test run on _your local_ machine.
- [x] Explain why you think the autograder is failing.

Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below. 

#### Which autograder check is failing?

📝 Default roll endpoint

#### What is happening?
Prints out the html of the site with the error Cannot POST /app/roll

#### Failed workflow run URL
https://github.com/comp426-2022-fall/a04-chaynickUNC/actions/runs/3520289500/jobs/5901066275

#### What should be happening?
Should return the default dice roll

#### Screenshots of your local test(s)
  {"sides":6,"dice":2,"rolls":1,"results":[1]}

#### Why do you think the autograder is failing? 
should accept the default dice roll

**Comment by jdmar3** [comment]
I am merging this issue with #6 because it is effectively the same thing. I will detail it there.
