### ISSUE TITLE
Autograder: [Exit Code 7]

### ISSUE THREAD

**Issue by aw811502** [comp426-2022-fall/a04#8]
#### Which autograder check is failing?
All endpoint checks fail with the same exit code 7:
<img width="473" alt="Screen Shot 2022-11-30 at 4 10 25 PM" src="https://user-images.githubusercontent.com/77753326/204909247-0a067948-bd95-4db9-bf47-f42b6e0d3b52.png">

Only the package.json check and node version check is passing.

#### What is happening?
Autograder script is running into an error "::error::Error: Exit with code: 7 and signal: null"

#### Failed workflow run URL
https://github.com/comp426-2022-fall/a04-aw811502/actions/runs/3587284435/jobs/6037450180

#### What should be happening?
Im expecting the script to call an api endpoint and show a response from the endpoint but it just shows an error.

#### Screenshots of your local test(s)
I have tested each endpoint on my local machine and get the correct output.

Workflow:  run "node server.js port=5555" and make a curl request "curl -s http://localhost:5555/app/roll/" and get the correct output "{"sides":6,"dice":2,"rolls":1,"results":[6]}".
<img width="506" alt="Screen Shot 2022-11-30 at 4 37 07 PM" src="https://user-images.githubusercontent.com/77753326/204913393-3e428df1-97fa-4a91-99b4-8e5cc9c0976a.png">

When running the bash commands from the readme, the output from the curl request does not get printed which is unexpected, but i think it might be because of my local machine, not the server.js code.
<img width="827" alt="Screen Shot 2022-11-30 at 4 41 17 PM" src="https://user-images.githubusercontent.com/77753326/204914061-e346d3b9-d888-4f90-ad7b-13f6ab3a485b.png">

#### Why do you think the autograder is failing? 
I think the autograder is running into an error when trying to call server.js.

**Comment by aw811502** [comment]
Some things i have tried to fix my autograder issues:

1. Rolled back repository all the way back to initial repository commit (from when I accepted the assignment) and copied back all the code. Was thinking that i may have accidentally deleted a file that the autograder required but this is not the case as the autograder still fails with the same error. Still works fine on local machine. https://github.com/comp426-2022-fall/a04-aw811502/actions/runs/3588258458/jobs/6039459053 

2. Added Logging throughout the server.js script that show up in autograder. Confirms that the script parses arguments correctly, imports dependencies correctly, and calls the roll function correctly. However, any logs I put within the endpoint functions are not called. Autograder still fails with the same error. https://github.com/comp426-2022-fall/a04-aw811502/actions/runs/3588453648/jobs/6039869924

3. Commented out all endpoint functions except for one. Did this for the root endpoint as well as the 404 error endpoint., but the respective tests still fail with the same error. Both work fine on local machine but fail on autograder. 
https://github.com/comp426-2022-fall/a04-aw811502/actions/runs/3588841256/jobs/6040652704

**Comment by aw811502** [comment]
Got the autograder to work after removing the shebang line from the roll.js script and using the native Math function instead of mathjs. Not sure why this changed the autograder behavior.

**Comment by jdmar3** [comment]
It didn't change the autograder behavior, necessarily. It changed the behavior of your script relative to the environment in which it was being run. Something about the way that your environment was set up was allowing this to run on your local, but not run a subshell in a pristine environment (every time the actions run, they spin up a runner that has a clean configuration). Given world enough and time, we could figure out exactly what it was.
